const Data = [
  {
    id: 1,
    name: "Gold Necklace",
    description: "18k gold necklace with diamond inlays.",
    category: "Jewelry",
    prise: 1500,
    status: "available",
    image: "gold-necklace.jpg",
  },

  {
    id: 33,
    name: "Bike",
    description: "18k gold necklace with diamond inlays.",
    category: "Bike",
    prise: 1500,
    status: "available",
    image: "gold-necklace.jpg",
  },
  {
    id: 34,
    name: "Bike 2",
    description: "18k gold necklace with diamond inlays.",
    category: "Bike",
    prise: 1500,
    status: "available",
    image: "gold-necklace.jpg",
  },
  {
    id: 35,
    name: "Car",
    description: "18k gold necklace with diamond inlays.",
    category: "Car",
    prise: 1500,
    status: "available",
    image: "gold-necklace.jpg",
  },
  {
    id:36,
    name: "Car 2",
    description: "18k gold necklace with diamond inlays.",
    category: "Car",
    prise: 1500,
    status: "car",
    image: "gold-necklace.jpg",
  },
  {
    id: 2,
    name: "Vintage Watch",
    description: "Rolex Submariner, limited edition.",
    category: "Watches",
    prise: 3500,
    status: "sold",
    image: "rolex-submariner.jpg",
  },
  {
    id: 3,
    name: "Guitar",
    description: "Fender Stratocaster, used, in excellent condition.",
    category: "Musical Instruments",
    prise: 800,
    status: "available",
    image: "fender-stratocaster.jpg",
  },
  {
    id: 4,
    name: "Old Coins Collection",
    description: "A collection of rare coins from the 1800s.",
    category: "Collectibles",
    prise: 2000,
    status: "pending",
    image: "old-coins.jpg",
  },
  {
    id: 5,
    name: "Smartphone",
    description: "iPhone 12, 128GB, in original condition.",
    category: "Electronics",
    prise: 600,
    status: "available",
    image: "iphone12.jpg",
  },
  {
    id: 6,
    name: "Vintage Camera",
    description: "Leica M3 film camera, in excellent working condition.",
    category: "antique",
    prise: 2200,
    status: "available",
    image: "leica-camera.jpg",
  },
  {
    id: 7,
    name: "Diamond Ring",
    description: "Platinum band with 1.5ct diamond.",
    category: "Jewelry",
    prise: 5000,
    status: "available",
    image: "diamond-ring.jpg",
  },
  {
    id: 8,
    name: "Antique Vase",
    description: "Porcelain vase from the Ming dynasty.",
    category: "Collectibles",
    prise: 3500,
    status: "sold",
    image: "antique-vase.jpg",
  },
  {
    id: 9,
    name: "Smart TV",
    description: "Samsung 55-inch 4K UHD Smart TV.",
    category: "Electronics",
    prise: 900,
    status: "available",
    image: "samsung-smart-tv.jpg",
  },
  {
    id: 10,
    name: "PlayStation 5",
    description: "Brand new, unopened PlayStation 5 console.",
    category: "Electronics",
    prise: 1200,
    status: "available",
    image: "playstation-5.jpg",
  },
  {
    id: 11,
    name: "Electric Guitar",
    description: "Gibson Les Paul, used but in great condition.",
    category: "Musical Instruments",
    prise: 2000,
    status: "available",
    image: "gibson-les-paul.jpg",
  },
  {
    id: 12,
    name: "Vintage Bicycle",
    description: "1950s Schwinn Roadster, restored.",
    category: "Vehicles",
    prise: 700,
    status: "available",
    image: "vintage-bicycle.jpg",
  },
  {
    id: 12,
    name: "Vintage Bicycle",
    description: "1950s Schwinn Roadster, restored.",
    category: "Vehicles",
    prise: 700,
    status: "available",
    image: "vintage-bicycle.jpg",
  }, {
    id: 12,
    name: "Vintage Bicycle",
    description: "1950s Schwinn Roadster, restored.",
    category: "Vehicles",
    prise: 700,
    status: "available",
    image: "vintage-bicycle.jpg",
  },
  {
    id: 13,
    name: "Silver Necklace",
    description: "925 sterling silver necklace with pendant.",
    category: "Jewelry",
    prise: 400,
    status: "available",
    image: "silver-necklace.jpg",
  },
  {
    id: 14,
    name: "Old Pocket Watch",
    description: "Antique pocket watch from 1920s, fully functional.",
    category: "antique",
    prise: 1500,
    status: "sold",
    image: "pocket-watch.jpg",
  },
  {
    id: 15,
    name: "Diamond Earrings",
    description: "0.8ct diamond stud earrings in 14k white gold.",
    category: "Jewelry",
    prise: 2000,
    status: "available",
    image: "diamond-earrings.jpg",
  },
  {
    id: 16,
    name: "Vintage Typewriter",
    description: "Smith Corona typewriter, fully restored.",
    category: "Collectibles",
    prise: 600,
    status: "available",
    image: "typewriter.jpg",
  },
  {
    id: 17,
    name: "Antique Mirror",
    description: "Gold-framed mirror from the 18th century.",
    category: "Furniture",
    prise: 2500,
    status: "available",
    image: "antique-mirror.jpg",
  },
  {
    id: 18,
    name: "Rolex Watch",
    description: "Rolex Datejust, pre-owned but in excellent condition.",
    category: "Watches",
    prise: 4500,
    status: "available",
    image: "rolex-datejust.jpg",
  },
  {
    id: 19,
    name: "MacBook Pro",
    description: "Apple MacBook Pro 16-inch, 1TB SSD.",
    category: "Electronics",
    prise: 2500,
    status: "sold",
    image: "macbook-pro.jpg",
  },
  {
    id: 20,
    name: "Comic Book Collection",
    description: "First edition Marvel comics, complete set.",
    category: "Collectibles",
    prise: 3500,
    status: "available",
    image: "comic-books.jpg",
  },
  {
    id: 21,
    name: "Gold Coins",
    description: "A collection of 10 1oz gold coins from the US Mint.",
    category: "Collectibles",
    prise: 12000,
    status: "available",
    image: "gold-coins.jpg",
  },
  {
    id: 22,
    name: "Vintage Radio",
    description: "1920s RCA radio, in working condition.",
    category: "Electronics",
    prise: 1100,
    status: "available",
    image: "vintage-radio.jpg",
  },
  {
    id: 23,
    name: "Fur Coat",
    description: "Luxurious mink fur coat in perfect condition.",
    category: "Apparel",
    prise: 2500,
    status: "pending",
    image: "mink-fur-coat.jpg",
  },
  {
    id: 24,
    name: "Antique Painting",
    description: "18th-century oil painting by famous artist.",
    category: "Art",
    prise: 8000,
    status: "available",
    image: "antique-painting.jpg",
  },
  {
    id: 25,
    name: "Bose Speakers",
    description: "Bose SoundLink Revolve portable Bluetooth speakers.",
    category: "Electronics",
    prise: 500,
    status: "available",
    image: "bose-speakers.jpg",
  },
  {
    id: 26,
    name: "Tiffany Bracelet",
    description: "Tiffany & Co. sterling silver bracelet with charm.",
    category: "Jewelry",
    prise: 1500,
    status: "sold",
    image: "tiffany-bracelet.jpg",
  },
  {
    id: 27,
    name: "Vintage Tricycle",
    description: "1930s child's tricycle, in great shape.",
    category: "Collectibles",
    prise: 600,
    status: "available",
    image: "vintage-tricycle.jpg",
  },
  {
    id: 28,
    name: "Antique Chess Set",
    description: "Hand-carved wooden chess set, complete with pieces.",
    category: "Collectibles",
    prise: 1200,
    status: "available",
    image: "chess-set.jpg",
  },
  {
    id: 29,
    name: "Luxury Handbag",
    description: "Chanel classic flap bag, used but in excellent condition.",
    category: "Fashion",
    prise: 3000,
    status: "available",
    image: "chanel-handbag.jpg",
  },
  {
    id: 30,
    name: "Gold Bar",
    description: "10 oz solid gold bar, certified authenticity.",
    category: "Precious Metals",
    prise: 18000,
    status: "sold",
    image: "gold-bar.jpg",
  },
];


export default Data;